<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simple_fal_importer"
 *
 * Auto generated by Extension Builder 2017-10-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple FAL Importer',
    'description' => 'This extensions will add a backend module which holds some functions to import any other extensions uploads to the uploads/ directory into the File Abstraction Layer.',
    'category' => 'plugin',
    'author' => 'Paul Beck',
    'author_email' => 'hi@toll-paul.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
